# Preload the image into memory
preload = /path/to/your/wallpaper.png

# Set the preloaded wallpaper to your monitor
# Leave the monitor blank before the comma to apply it to all monitors
wallpaper = ,/path/to/your/wallpaper.png


splash = false